AWSTemplateFormatVersion: "2010-09-09"
Description: This is a CFN template to create VPCs for Lab 4.
Parameters:
  TagUser:
    Type: String
  TagLesson:
    Type: String
  TagLab:
    Type: String
  VPCCIDR:
    Type: String
  SubnetCIDR:
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCIDR
      Tags: 
        - Key: user
          Value: !Ref TagUser
        - Key: stelligent-u-lesson
          Value: !Ref TagLesson
        - Key: stelligent-u-lab
          Value: !Ref TagLab
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: !Ref SubnetCIDR
      Tags: 
        - Key: user
          Value: !Ref TagUser
        - Key: stelligent-u-lesson
          Value: !Ref TagLesson
        - Key: stelligent-u-lab
          Value: !Ref TagLab
Outputs:
  VPCID:
    Description: VPC ID
    Value: !Ref VPC
  SubnetID:
    Description: Subnet ID
    Value: !Ref Subnet