AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  UbuntuAMI:
    Type: String
    Default: '/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id'
  VPCID:
    Type: String
  SubnetID:
    Type: String
  TagUser:
    Type: String
  TagLesson:
    Type: String
  TagLab:
    Type: String
  KeyName:
    Type: String
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags: 
        - Key: user
          Value: !Ref TagUser
        - Key: stelligent-u-lesson
          Value: !Ref TagLesson
        - Key: stelligent-u-lab
          Value: !Ref TagLab
  