AWSTemplateFormatVersion: "2010-09-09"
Description: This is a CFN template to create an IAM Role for Lab 3.2.
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: arn:aws:iam::324320755747:user/zachery.cox.labs
          Action: sts:AssumeRole
      RoleName: zachroleplzdelete
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess