pipeline {

    agent { label 'test' }
    triggers {
        cron('*/5 * * * *')
    }
    environment { 
        lab = '14'
    }
    stages{
        stage("One"){
            steps{

                sh 'ls -alh'
                sh 'pwd'
                sh 'whoami'
                sh 'git clone https://github.com/zacherytcox/stelligent-u.git ./tmp'
                sh 'rm -rf ./tmp'

            }
        }

        stage("Two"){
            tools {

                maven 'maven' 
            }
            steps{
                
                sh 'ls -alh'
                sh 'pwd'
                sh 'whoami'
                sh 'cd 14-Jenkins/my-app && mvn clean validate compile test package' //` of the root Java project source "`my-app`"
                archiveArtifacts artifacts: '14-Jenkins/my-app/target/my-app*'
                
            }
        }

        stage("S3"){
            steps{
                
                s3Upload {

                }
                archiveArtifacts artifacts: '14-Jenkins/my-app/target/my-app*'
                
            }
        }
    }

}